'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';
type Operation={id:string;task_type:string;execution_mode:string;status:string;attempt:number;max_attempts:number;ai_explanation?:string;error_message?:string;created_at:string};
async function request(path:string,token:string,init:RequestInit={}){const response=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});if(!response.ok){const p=await response.json().catch(()=>({detail:response.statusText}));throw new Error(p.detail||'Request failed')}return response.status===204?null:response.json()}
export default function Home(){const[token,setToken]=useState('');const[email,setEmail]=useState('ops@acme.test');const[password,setPassword]=useState('AcmeDemo123!');const[operations,setOperations]=useState<Operation[]>([]);const[usage,setUsage]=useState({used:0,quota:0,remaining:0});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[mode,setMode]=useState('normal');const[question,setQuestion]=useState('Why did my latest operation fail?');const[answer,setAnswer]=useState('');
const refresh=useCallback(async()=>{if(!token)return;try{const [ops,u]=await Promise.all([request('/v1/operations',token),request('/v1/usage',token)]);setOperations(ops.items);setUsage(u)}catch(e){setError((e as Error).message)}},[token]);useEffect(()=>{const initial=setTimeout(()=>void refresh(),0);const id=setInterval(()=>void refresh(),3000);return()=>{clearTimeout(initial);clearInterval(id)}},[refresh]);
async function login(e:FormEvent){e.preventDefault();setError('');try{const response=await fetch(API+'/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json();if(!response.ok)throw new Error(body.detail||'Login failed');setToken(body.access_token)}catch(e){setError((e as Error).message)}}
async function create(){setBusy(true);setError('');try{await request('/v1/operations',token,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({task_type:'acme.ticket.process',execution_mode:'PRIVATE',target_url:'http://acme:8090/work',payload:{ticket_id:`ACME-${Date.now()}`,mode},max_attempts:3})});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function cancel(id:string){try{await request('/v1/operations/'+id,token,{method:'DELETE'});refresh()}catch(e){setError((e as Error).message)}}
async function redrive(id:string){try{await request('/v1/operations/'+id+'/redrive',token,{method:'POST'});refresh()}catch(e){setError((e as Error).message)}}
async function ask(){setError('');setAnswer('');try{const result=await request('/v1/assistant',token,{method:'POST',body:JSON.stringify({question})});setAnswer(result.answer)}catch(e){setError((e as Error).message)}}
if(!token)return <main className="login"><section className="loginCard"><div className="mark">N</div><p className="eyebrow">NEXORA PRIVATE OPERATIONS</p><h1>Know what happened.<br/>Without moving the job.</h1><p className="muted">Sign in to the Acme customer console.</p><form onSubmit={login}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button></form></section></main>;
return <main><header><div><div className="brand"><span className="mark small">N</span>Nexora</div><p>Customer operations console</p></div><button className="ghost" onClick={()=>setToken('')}>Sign out</button></header><section className="hero"><div><p className="eyebrow">ACME SUPPORT · PRIVATE WORKER ONLINE</p><h1>Operations, explained.</h1><p className="muted">Jobs execute inside Acme&apos;s network. Nexora coordinates, observes, and explains.</p></div><div className="usage"><span>Monthly usage</span><strong>{usage.used.toLocaleString()} <small>/ {usage.quota.toLocaleString()}</small></strong><div><i style={{width:`${usage.quota?Math.min(100,usage.used/usage.quota*100):0}%`}}/></div></div></section><section className="controls"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="normal">Successful job</option><option value="fail">Retryable failure</option><option value="reject">Permanent rejection</option><option value="slow">Lease / timeout test</option></select><button onClick={create} disabled={busy}>{busy?'Submitting…':'Run private operation'}</button><button className="ghost" onClick={refresh}>Refresh</button></section>{error&&<p className="error banner">{error}</p>}<section className="assistant"><div><p className="eyebrow">AI OPERATIONS ASSISTANT</p><h2>Ask about recent runs</h2></div><div className="ask"><input value={question} onChange={e=>setQuestion(e.target.value)}/><button onClick={ask}>Ask Nexora</button></div>{answer&&<p>{answer}</p>}</section><section className="panel"><div className="panelTitle"><h2>Recent operations</h2><span>{operations.length} shown</span></div><div className="table"><div className="row head"><span>Operation</span><span>Execution</span><span>Status</span><span>Attempts</span><span>Created</span><span/></div>{operations.map(op=><div className="row" key={op.id}><span><b>{op.task_type}</b><code>{op.id.slice(0,8)}</code>{op.ai_explanation&&<em>{op.ai_explanation}</em>}{op.error_message&&<em className="failure">{op.error_message}</em>}</span><span><span className="private">↗ {op.execution_mode}</span></span><span><span className={'status '+op.status.toLowerCase()}>{op.status}</span></span><span>{op.attempt} / {op.max_attempts}</span><span>{new Date(op.created_at).toLocaleString()}</span><span>{['PENDING','QUEUED','RUNNING','RETRYING'].includes(op.status)&&<button className="link" onClick={()=>cancel(op.id)}>Cancel</button>}{['FAILED','DEAD_LETTERED'].includes(op.status)&&<button className="link" onClick={()=>redrive(op.id)}>Redrive</button>}</span></div>)}{!operations.length&&<div className="empty">No operations yet. Run the first private job.</div>}</div></section></main>}
