'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';
type Tenant={id:string;name:string;slug:string;monthly_quota:number;concurrency_limit:number};type Op={id:string;tenant_id:string;task_type:string;status:string;execution_mode:string;created_at:string};type Usage={tenant_id:string;name:string;quota:number;used:number};
async function api(path:string,token:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});const body=r.status===204?null:await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||r.statusText);return body}
export default function Admin(){const[token,setToken]=useState('');const[email,setEmail]=useState('admin@nexora.local');const[password,setPassword]=useState('ChangeMe123!');const[tenants,setTenants]=useState<Tenant[]>([]);const[ops,setOps]=useState<Op[]>([]);const[usage,setUsage]=useState<Usage[]>([]);const[error,setError]=useState('');const[showNew,setShowNew]=useState(false);
const refresh=useCallback(async()=>{if(!token)return;try{const[t,o,u]=await Promise.all([api('/v1/admin/tenants',token),api('/v1/admin/operations',token),api('/v1/admin/usage',token)]);setTenants(t.items);setOps(o.items);setUsage(u.items)}catch(e){setError((e as Error).message)}},[token]);useEffect(()=>{const initial=setTimeout(()=>void refresh(),0);const i=setInterval(()=>void refresh(),5000);return()=>{clearTimeout(initial);clearInterval(i)}},[refresh]);
async function login(e:FormEvent){e.preventDefault();try{const r=await fetch(API+'/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const b=await r.json();if(!r.ok)throw new Error(b.detail||'Login failed');if(b.role!=='admin')throw new Error('Administrator role required');setToken(b.access_token)}catch(e){setError((e as Error).message)}}
async function createTenant(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{await api('/v1/admin/tenants',token,{method:'POST',body:JSON.stringify({...data,monthly_quota:Number(data.monthly_quota),concurrency_limit:Number(data.concurrency_limit)})});setShowNew(false);refresh()}catch(e){setError((e as Error).message)}}
if(!token)return <main className="login"><form onSubmit={login}><div className="logo">N</div><p className="eyebrow">NEXORA CONTROL PLANE</p><h1>Platform administration</h1><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button></form></main>;
const running=ops.filter(o=>o.status==='RUNNING').length,failed=ops.filter(o=>['FAILED','DEAD_LETTERED'].includes(o.status)).length,totalUsage=usage.reduce((n,u)=>n+u.used,0);return <main><aside><div className="brand"><span className="logo small">N</span>Nexora</div><nav><a className="active">Overview</a><a>Tenants</a><a>Operations</a><a>Usage</a><a>Webhooks</a></nav><button className="outline" onClick={()=>setToken('')}>Sign out</button></aside><section className="content"><header><div><p className="eyebrow">CONTROL PLANE</p><h1>System overview</h1></div><button onClick={()=>setShowNew(true)}>Add tenant</button></header>{error&&<p className="error alert">{error}</p>}<div className="metrics"><article><span>Active tenants</span><strong>{tenants.length}</strong><small>isolated workspaces</small></article><article><span>Running now</span><strong>{running}</strong><small>private + cloud</small></article><article><span>Failed / DLQ</span><strong className={failed?'red':''}>{failed}</strong><small>requires attention</small></article><article><span>Monthly units</span><strong>{totalUsage}</strong><small>append-only ledger</small></article></div><div className="grid"><section className="panel wide"><div className="title"><h2>Latest operations</h2><button className="text" onClick={refresh}>Refresh</button></div><div className="table"><div className="row head"><span>Task</span><span>Tenant</span><span>Execution</span><span>Status</span><span>Created</span></div>{ops.slice(0,12).map(o=><div className="row" key={o.id}><span><b>{o.task_type}</b><code>{o.id.slice(0,8)}</code></span><span><code>{o.tenant_id.slice(0,8)}</code></span><span>{o.execution_mode}</span><span><i className={'status '+o.status.toLowerCase()}>{o.status}</i></span><span>{new Date(o.created_at).toLocaleString()}</span></div>)}</div></section><section className="panel"><div className="title"><h2>Tenant usage</h2></div>{usage.map(u=><div className="tenant" key={u.tenant_id}><div><b>{u.name}</b><span>{u.used} / {u.quota}</span></div><div><i style={{width:`${Math.min(100,u.quota?u.used/u.quota*100:0)}%`}}/></div></div>)}</section></div>{showNew&&<div className="modal"><form onSubmit={createTenant}><div className="title"><h2>Create tenant</h2><button type="button" className="text" onClick={()=>setShowNew(false)}>Close</button></div><label>Company name<input name="name" required/></label><label>Slug<input name="slug" pattern="[a-z0-9-]+" required/></label><label>Owner email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="password" minLength={10} required/></label><div className="split"><label>Monthly quota<input name="monthly_quota" type="number" defaultValue="10000"/></label><label>Concurrency<input name="concurrency_limit" type="number" defaultValue="5"/></label></div><button>Create tenant</button></form></div>}</section></main>}
